#include "assets/font.hpp"
#include "assets/image.hpp"
#include "assets/shader_source.hpp"
#include "core/application.hpp"
#include "renderer/renderer.hpp"
#include "scene/scene.hpp"
#include "utility/macro.hpp"
